"""removing language field from comment

Revision ID: 91135169808e
Revises: 19f703fecfc5
Create Date: 2026-06-13 12:54:09.600662

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '91135169808e'
down_revision = '19f703fecfc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', mysql.VARCHAR(length=5), nullable=True))

    # ### end Alembic commands ###
